package com.powermediaplayer.data.repository

import com.powermediaplayer.data.db.dao.FavouriteBookmarkDao
import com.powermediaplayer.data.db.dao.HistoryBookmarkDao
import com.powermediaplayer.data.db.dao.HistoryFavouriteDao
import com.powermediaplayer.data.db.dao.PlaybackHistoryDao
import com.powermediaplayer.data.db.entity.FavouriteBookmarkEntity
import com.powermediaplayer.data.db.entity.HistoryBookmarkEntity
import com.powermediaplayer.data.db.entity.HistoryFavouriteEntity
import com.powermediaplayer.data.db.entity.PlaybackHistoryEntity
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.map
import javax.inject.Inject
import javax.inject.Singleton

/**
 * One source of truth for the Last Played tab. Each play produces a
 * NEW [PlaybackHistoryEntity] row (autogenerated id), so the same
 * media file can appear multiple times in the Recents list (one row
 * per session). [HistoryFavouriteEntity] rows are full snapshots —
 * pinning a Recents row copies title/artwork/source/etc. plus its
 * bookmarks into independent tables, so deleting the original
 * Recents row never affects the pin.
 *
 * Three independent bookmark tables:
 *   - [com.powermediaplayer.data.db.dao.BookmarkDao] : per-mediaUri,
 *     editable from the Player tab (live).
 *   - [HistoryBookmarkDao] : per-session snapshot, populated when the
 *     user adds a Player bookmark during that session. Independent of
 *     the Player table after creation.
 *   - [FavouriteBookmarkDao] : per-pin snapshot, copied from the
 *     Recents row's [HistoryBookmarkDao] entries at pin time.
 *     Independent thereafter.
 */
@Singleton
class LastPlayedRepository @Inject constructor(
    private val historyDao: PlaybackHistoryDao,
    private val favDao: HistoryFavouriteDao,
    private val historyBookmarkDao: HistoryBookmarkDao,
    private val favouriteBookmarkDao: FavouriteBookmarkDao,
    private val pinnedAlbumDao: com.powermediaplayer.data.db.dao.PinnedAlbumDao
) {

    /**
     * UI-facing pinned-album shape. The user-visible behaviour is
     * locked: tap row → expand tracks; tap track → play that one.
     */
    data class PinnedAlbumItem(
        val id: Long,
        val albumKey: String,
        val title: String,
        val artist: String,
        val artworkUri: String?,
        val pinOrder: Int,
        val pinnedAtMs: Long,
        val trackCount: Int
    )

    data class AlbumTrackToPin(
        val mediaUri: String,
        val title: String,
        val durationMs: Long
    )

    /**
     * Combined cap across track pins + album pins. Repository enforces
     * a single shared limit so the user gets a stable promise: "you can
     * pin up to 10 things, tracks or albums".
     */
    suspend fun pinSlotsUsed(): Int = favDao.count() + pinnedAlbumDao.count()

    val PIN_CAP: Int = 10

    fun observePinnedAlbums(): kotlinx.coroutines.flow.Flow<List<PinnedAlbumItem>> =
        kotlinx.coroutines.flow.combine(
            pinnedAlbumDao.observeAll(),
            // Audit 4.6 — the old combine(flowOf(Unit)) emitted once and
            // never refreshed counts; this JOIN-count flow re-emits on
            // Room invalidation of EITHER table, and replaces the N
            // per-album snapshot queries per emission.
            pinnedAlbumDao.observeTrackCounts()
        ) { albums, counts ->
            val countById = counts.associate { it.id to it.trackCount }
            albums.map { a ->
                PinnedAlbumItem(
                    id = a.id,
                    albumKey = a.albumKey,
                    title = a.title,
                    artist = a.artist,
                    artworkUri = a.artworkUri,
                    pinOrder = a.pinOrder,
                    pinnedAtMs = a.pinnedAtMs,
                    trackCount = countById[a.id] ?: 0
                )
            }
        }

    fun observeAlbumTracks(albumId: Long) =
        pinnedAlbumDao.observeTracks(albumId)

    suspend fun pinAlbum(
        albumKey: String,
        title: String,
        artist: String,
        artworkUri: String?,
        tracks: List<AlbumTrackToPin>
    ): Result<Unit> {
        val used = pinSlotsUsed()
        if (used >= PIN_CAP) {
            return Result.failure(
                IllegalStateException("Favourites full ($used/$PIN_CAP) — unpin one first")
            )
        }
        val order = used // append to end
        val albumId = pinnedAlbumDao.insert(
            com.powermediaplayer.data.db.entity.PinnedAlbumEntity(
                albumKey = albumKey,
                title = title,
                artist = artist,
                artworkUri = artworkUri,
                pinOrder = order,
                pinnedAtMs = System.currentTimeMillis()
            )
        )
        tracks.forEachIndexed { idx, t ->
            pinnedAlbumDao.insertTrack(
                com.powermediaplayer.data.db.entity.PinnedAlbumTrackEntity(
                    albumId = albumId,
                    mediaUri = t.mediaUri,
                    title = t.title,
                    durationMs = t.durationMs,
                    trackIndex = idx
                )
            )
        }
        return Result.success(Unit)
    }

    suspend fun unpinAlbum(id: Long) {
        pinnedAlbumDao.delete(id)
        // Re-compact pinOrders so the next pin fills the lowest free slot.
        val rest = pinnedAlbumDao.snapshot()
        rest.forEachIndexed { idx, a ->
            if (a.pinOrder != idx) pinnedAlbumDao.setOrder(a.id, idx)
        }
    }

    data class HistoryItem(
        val id: Long,                  // session id (NOT mediaUri)
        val mediaUri: String,
        val title: String,
        val subtitle: String,
        val artworkUri: String?,
        val source: Source,
        val mediaKindOrdinal: Int,
        val lastPositionMs: Long,
        val durationMs: Long,
        val lastPlayedAt: Long,
        val isPinned: Boolean,         // any pin currently exists for this mediaUri (UI hint only)
        val pinOrder: Int              // -1 if not applicable; pin's own pinOrder when item is from favourites
    )

    enum class Source { LOCAL, DRIVE, SPOTIFY }

    /**
     * Most recently inserted history row id. Used by PlayerViewModel
     * to attach Player-tab bookmark adds to the correct session
     * snapshot. Null until the first recordPlay of the app's lifetime.
     */
    private val _currentSessionId = MutableStateFlow<Long?>(null)
    val currentSessionId: StateFlow<Long?> = _currentSessionId.asStateFlow()

    /**
     * Insert a NEW play session and return its id. Trims the dynamic
     * Recents list to its 10-item cap (pinned snapshots are exempt
     * because they live in their own table now).
     */
    suspend fun recordPlay(row: PlaybackHistoryEntity): Long {
        val id = historyDao.insertSession(row)
        _currentSessionId.value = id
        trimToCap()
        return id
    }

    /**
     * Backfill: clear stored borrowed album-art URIs from existing history
     * rows (the library scan now suppresses these covers at source). No-op
     * when the set is empty.
     */
    suspend fun clearBorrowedArtwork(borrowedAlbumArtUris: Set<String>) {
        if (borrowedAlbumArtUris.isEmpty()) return
        historyDao.clearArtworkFor(borrowedAlbumArtUris.toList())
    }

    /**
     * Adopt an existing history row as the current session so subsequent
     * Player-tab bookmark adds mirror into ITS snapshot table — without
     * creating a duplicate Recents row. Used by:
     *  - Cold-start auto-resume: the most-recent row is restored into the
     *    player; we want bookmarks added during that listen to attach to
     *    that same row, not a new one.
     *  - Notification-tap resume: the service has already loaded the
     *    media item; we adopt the row whose mediaUri matches.
     * Idempotent — safe to call multiple times with the same id.
     */
    fun adoptSession(id: Long) {
        _currentSessionId.value = id
    }

    /** Update the current row's resume position (5s tick from PlayerVM). */
    suspend fun updatePosition(id: Long, posMs: Long) {
        historyDao.updatePosition(id, posMs)
    }

    /** Legacy URI-keyed update — touches the most-recent row for that uri. */
    suspend fun updatePositionByUri(uri: String, posMs: Long) {
        historyDao.updatePositionByUri(uri, posMs)
    }

    /** Persist enriched display title/author onto the most-recent row for a
     *  uri, so a later auto-resume shows the proper tags (not the filename). */
    suspend fun updateDisplayByUri(uri: String, title: String, subtitle: String) {
        historyDao.updateDisplayByUri(uri, title, subtitle)
    }

    /** Delete a single Recents row (and its bookmarks via FK CASCADE). */
    suspend fun delete(id: Long) {
        historyDao.delete(id)
    }

    /**
     * vc31 undo support — snapshot a row + its session bookmarks BEFORE a
     * delete so a swipe can be reversed. Returns null if the row is gone.
     */
    suspend fun snapshotForUndo(
        id: Long
    ): Pair<PlaybackHistoryEntity, List<HistoryBookmarkEntity>>? {
        val row = historyDao.get(id) ?: return null
        val bookmarks = historyBookmarkDao.snapshotForSession(id)
        return row to bookmarks
    }

    /**
     * Re-insert a previously-deleted row + its bookmarks (Undo). The
     * original autogenerated ids are preserved (the entities still carry
     * them), so FK links restore intact. Deliberately does NOT touch
     * [currentSessionId] — undo is a pure data restore, not a resume.
     */
    suspend fun restoreRow(
        row: PlaybackHistoryEntity,
        bookmarks: List<HistoryBookmarkEntity>
    ) {
        historyDao.insertSession(row)
        bookmarks.forEach { historyBookmarkDao.insert(it) }
    }

    /**
     * Delete every Recents row + their session bookmarks (cascade).
     * Pinned snapshots in [HistoryFavouriteEntity] / [FavouriteBookmarkEntity]
     * are independent and survive — only the dynamic recent-plays list
     * is cleared.
     */
    suspend fun clearAllRecents() {
        historyDao.deleteAll()
        _currentSessionId.value = null
    }

    suspend fun mostRecent(): PlaybackHistoryEntity? = historyDao.mostRecent()

    /**
     * Recents view: every history row, joined with whether the same
     * mediaUri is currently pinned (so the UI can show a filled star).
     * Sorted by recency. Pinned status is a HINT only — pinned rows
     * still appear in Recents (the user explicitly asked for this:
     * pinning does NOT remove from Recents).
     */
    fun observeDynamic(): Flow<List<HistoryItem>> =
        kotlinx.coroutines.flow.combine(
            historyDao.observeAll(),
            favDao.observeAll()
        ) { hist, favs ->
            val pinnedUris = favs.map { it.mediaUri }.toSet()
            hist.take(20).map { e ->
                HistoryItem(
                    id = e.id,
                    mediaUri = e.mediaUri,
                    title = e.title,
                    subtitle = e.subtitle,
                    artworkUri = e.artworkUri,
                    source = sourceOf(e.source),
                    mediaKindOrdinal = e.mediaKindOrdinal,
                    lastPositionMs = e.lastPositionMs,
                    durationMs = e.durationMs,
                    lastPlayedAt = e.lastPlayedAt,
                    isPinned = pinnedUris.contains(e.mediaUri),
                    pinOrder = -1
                )
            }
        }

    /**
     * Pinned view: each [HistoryFavouriteEntity] is a stand-alone
     * snapshot, surfaced as a HistoryItem so the UI doesn't need to
     * know it's a different table. The id field carries the
     * favourite's own id (NOT a history id) — caller should treat
     * Recents and Pinned ids as separate ID spaces.
     */
    fun observePinned(): Flow<List<HistoryItem>> =
        favDao.observeAll().map { favs ->
            favs.sortedBy { it.pinOrder }.map { f ->
                HistoryItem(
                    id = f.id,
                    mediaUri = f.mediaUri,
                    title = f.title,
                    subtitle = f.subtitle,
                    artworkUri = f.artworkUri,
                    source = sourceOf(f.source),
                    mediaKindOrdinal = f.mediaKindOrdinal,
                    lastPositionMs = f.lastPositionMs,
                    durationMs = f.durationMs,
                    lastPlayedAt = f.pinnedAtMs,
                    isPinned = true,
                    pinOrder = f.pinOrder
                )
            }
        }

    /**
     * Pin a Recents row. Snapshots its data + bookmarks into the
     * favourites tables. Returns Failure when 10 pins already exist.
     */
    suspend fun pinSession(historyId: Long): Result<Unit> {
        // Shared cap with pinned albums: both compete for the same 10 slots.
        val used = pinSlotsUsed()
        if (used >= PIN_CAP) return Result.failure(
            IllegalStateException("Favourites full ($used/$PIN_CAP)")
        )
        val n = favDao.count() // pin order within the favourites table
        val src = historyDao.get(historyId)
            ?: return Result.failure(IllegalStateException("Session $historyId not found"))
        val favId = favDao.insert(
            HistoryFavouriteEntity(
                mediaUri = src.mediaUri,
                title = src.title,
                subtitle = src.subtitle,
                artworkUri = src.artworkUri,
                source = src.source,
                mediaKindOrdinal = src.mediaKindOrdinal,
                lastPositionMs = src.lastPositionMs,
                durationMs = src.durationMs,
                pinOrder = n,
                pinnedAtMs = System.currentTimeMillis()
            )
        )
        // Snapshot every Recents bookmark for this session into the
        // independent favourite_bookmarks table.
        val sessionBookmarks = historyBookmarkDao.snapshotForSession(historyId)
        sessionBookmarks.forEach { hb ->
            favouriteBookmarkDao.insert(
                FavouriteBookmarkEntity(
                    favouriteId = favId,
                    positionMs = hb.positionMs,
                    label = hb.label
                )
            )
        }
        return Result.success(Unit)
    }

    /** Remove a pin (and its snapshot bookmarks via FK CASCADE). */
    suspend fun unpin(favouriteId: Long) {
        favDao.delete(favouriteId)
        compactPinOrders()
    }

    /** §C7 — exposed for callers that need the row's mediaUri. */
    suspend fun snapshotFavourites() = favDao.snapshot()

    /**
     * Reorder a pin to position [newOrder] (0-based). Other pins are
     * shifted to maintain a contiguous 0..n-1 ordering.
     */
    suspend fun reorderPinned(favouriteId: Long, newOrder: Int) {
        val pins = favDao.snapshot().toMutableList()
        val cur = pins.indexOfFirst { it.id == favouriteId }
        if (cur == -1) return
        val target = newOrder.coerceIn(0, pins.size - 1)
        if (target == cur) return
        val item = pins.removeAt(cur)
        pins.add(target, item)
        pins.forEachIndexed { idx, p ->
            if (p.pinOrder != idx) favDao.setOrder(p.id, idx)
        }
    }

    // ── Per-section bookmark APIs ─────────────────────────────────

    /**
     * Mirror a Player-tab bookmark add into the session's snapshot.
     * Caller is PlayerViewModel; on each addBookmarkHere the
     * currentSessionId is fetched and we attach a snapshot row here.
     */
    suspend fun addSessionBookmark(historyId: Long, positionMs: Long, label: String): Long {
        return historyBookmarkDao.insert(
            HistoryBookmarkEntity(
                historyId = historyId,
                positionMs = positionMs,
                label = label
            )
        )
    }

    suspend fun deleteSessionBookmark(id: Long) = historyBookmarkDao.delete(id)

    fun observeSessionBookmarks(historyId: Long): Flow<List<HistoryBookmarkEntity>> =
        historyBookmarkDao.observeForSession(historyId)

    suspend fun deleteFavouriteBookmark(id: Long) = favouriteBookmarkDao.delete(id)

    fun observeFavouriteBookmarks(favouriteId: Long): Flow<List<FavouriteBookmarkEntity>> =
        favouriteBookmarkDao.observeForFavourite(favouriteId)

    // ── Internals ─────────────────────────────────────────────────

    private suspend fun compactPinOrders() {
        val pins = favDao.snapshot()
        pins.forEachIndexed { idx, p ->
            if (p.pinOrder != idx) favDao.setOrder(p.id, idx)
        }
    }

    /**
     * Cap the Recents list at 20 rows. Pinned snapshots are in their
     * own table now and never count toward the cap.
     */
    private suspend fun trimToCap() {
        val rows = historyDao.snapshot()
        if (rows.size > 20) {
            val toDelete = rows.drop(20).map { it.id }
            historyDao.deleteMany(toDelete)
        }
    }

    private fun sourceOf(s: String): Source = when (s) {
        "DRIVE" -> Source.DRIVE
        "SPOTIFY" -> Source.SPOTIFY
        else -> Source.LOCAL
    }
}
