package com.powermediaplayer.data.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.powermediaplayer.data.db.entity.PlaybackHistoryEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface PlaybackHistoryDao {
    /**
     * Insert a NEW play session. Returns the autogenerated row id so
     * the caller can use it to attach session-scoped bookmarks via
     * [HistoryBookmarkDao].
     */
    @Insert
    suspend fun insertSession(row: PlaybackHistoryEntity): Long

    @Query("SELECT * FROM playback_history ORDER BY lastPlayedAt DESC")
    fun observeAll(): Flow<List<PlaybackHistoryEntity>>

    /** §10.1 alarm picker — top N most-recent rows. */
    @Query("SELECT * FROM playback_history ORDER BY lastPlayedAt DESC LIMIT :limit")
    fun recent(limit: Int): Flow<List<PlaybackHistoryEntity>>

    /** One-shot snapshot — used by trimToCap. */
    @Query("SELECT * FROM playback_history ORDER BY lastPlayedAt DESC")
    suspend fun snapshot(): List<PlaybackHistoryEntity>

    @Query("SELECT * FROM playback_history ORDER BY lastPlayedAt DESC LIMIT 1")
    suspend fun mostRecent(): PlaybackHistoryEntity?

    /**
     * Update position for a specific session (id-based) — used by the
     * 5-second persist tick in PlayerViewModel. Avoid wildcarding
     * across all sessions of the same mediaUri because each session
     * carries its own resume position.
     */
    @Query("UPDATE playback_history SET lastPositionMs = :pos WHERE id = :id")
    suspend fun updatePosition(id: Long, pos: Long)

    /** Compatibility: legacy callers that key by URI update the most recent row. */
    @Query(
        "UPDATE playback_history SET lastPositionMs = :pos " +
            "WHERE id = (SELECT id FROM playback_history WHERE mediaUri = :uri " +
            "ORDER BY lastPlayedAt DESC LIMIT 1)"
    )
    suspend fun updatePositionByUri(uri: String, pos: Long)

    /** Update the display title/subtitle of the most-recent row for a uri.
     *  Used when embedded tags are extracted AFTER the row was first written
     *  with the filename — so auto-resume shows the proper title/author. */
    @Query(
        // Keep the existing subtitle (e.g. the 'DRIVE' source label) when the
        // extracted artist is blank, rather than wiping it to ''.
        "UPDATE playback_history SET title = :title, " +
            "subtitle = CASE WHEN :subtitle = '' THEN subtitle ELSE :subtitle END " +
            "WHERE id = (SELECT id FROM playback_history WHERE mediaUri = :uri " +
            "ORDER BY lastPlayedAt DESC LIMIT 1)"
    )
    suspend fun updateDisplayByUri(uri: String, title: String, subtitle: String)

    /** Persist the cover-art URI (a durable cache-file path for embedded art)
     *  onto the most-recent row for a uri, so Last Played thumbnails + resume
     *  show the real cover, not the (often null) Drive thumbnail. */
    @Query(
        "UPDATE playback_history SET artworkUri = :artworkUri " +
            "WHERE id = (SELECT id FROM playback_history WHERE mediaUri = :uri " +
            "ORDER BY lastPlayedAt DESC LIMIT 1)"
    )
    suspend fun updateArtworkByUri(uri: String, artworkUri: String)

    @Query("DELETE FROM playback_history WHERE id = :id")
    suspend fun delete(id: Long)

    @Query("DELETE FROM playback_history WHERE id IN (:ids)")
    suspend fun deleteMany(ids: List<Long>)

    /**
     * Null out artworkUri on rows that captured a BORROWED MediaStore
     * album-art cover (an albumId bucketing unrelated files) before the
     * library scan started suppressing it — so old Last Played rows stop
     * showing the wrong cover without a manual "Clear all".
     */
    @Query("UPDATE playback_history SET artworkUri = NULL WHERE artworkUri IN (:uris)")
    suspend fun clearArtworkFor(uris: List<String>)

    @Query("SELECT * FROM playback_history WHERE id = :id")
    suspend fun get(id: Long): PlaybackHistoryEntity?

    /** Resume position of the most-recent row for a uri — drives the podcast
     *  episode-row progress marker (in-progress vs played). Null = never played. */
    @Query(
        "SELECT lastPositionMs FROM playback_history WHERE mediaUri = :uri " +
            "ORDER BY lastPlayedAt DESC LIMIT 1"
    )
    fun observePositionFor(uri: String): Flow<Long?>

    @Query("DELETE FROM playback_history")
    suspend fun deleteAll()

    // ── Stats queries (§C2) ────────────────────────────────────────
    /** Aggregate (label, count) row used by top-N stats queries. */
    data class CountRow(val label: String, val plays: Int)
    /** Aggregate (label, totalMs) row used by listen-time queries. */
    data class DurationRow(val label: String, val totalMs: Long)

    @Query("SELECT COUNT(*) FROM playback_history")
    suspend fun totalPlays(): Int

    /**
     * Sum of lastPositionMs across every history row — a proxy for
     * "total time listened" (it's the saved resume position, not a
     * cumulative listen counter, but for "rough lifetime stats" it's
     * the closest available without a per-row listen log).
     */
    @Query("SELECT IFNULL(SUM(lastPositionMs), 0) FROM playback_history")
    suspend fun totalListenedMs(): Long

    @Query(
        "SELECT title AS label, COUNT(*) AS plays " +
            "FROM playback_history GROUP BY title ORDER BY plays DESC LIMIT 5"
    )
    suspend fun topTitles(): List<CountRow>

    @Query(
        "SELECT subtitle AS label, COUNT(*) AS plays " +
            "FROM playback_history WHERE subtitle != '' " +
            "GROUP BY subtitle ORDER BY plays DESC LIMIT 5"
    )
    suspend fun topSubtitles(): List<CountRow>

    @Query("SELECT MAX(durationMs) FROM playback_history")
    suspend fun longestTrackDurationMs(): Long?

    // ── #16 enriched-metadata Drive search ──────────────────────────
    /** Search DRIVE-source rows by enriched title/author (subtitle). mediaUri
     *  here is the Drive download/stream URL (recordCloudPlay stores it), so a
     *  hit maps back to a playable CloudMediaItem. Distinct by mediaUri
     *  (most-recent row wins). ESCAPE handles literal % / _ in the needle. */
    @Query(
        "SELECT * FROM playback_history " +
            "WHERE source = 'DRIVE' AND id IN (" +
            "  SELECT MAX(id) FROM playback_history WHERE source='DRIVE' GROUP BY mediaUri" +
            ") AND (title LIKE :pattern ESCAPE '\\' OR subtitle LIKE :pattern ESCAPE '\\') " +
            "ORDER BY lastPlayedAt DESC LIMIT 50"
    )
    suspend fun searchDriveMetadata(pattern: String): List<PlaybackHistoryEntity>

    /** #16 — is this Drive uri already enriched into history? (skip re-enrich). */
    @Query("SELECT COUNT(*) FROM playback_history WHERE source='DRIVE' AND mediaUri = :uri")
    suspend fun countDriveRow(uri: String): Int
}
