package com.powermediaplayer.data.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import com.powermediaplayer.data.db.entity.PlaybackHistoryEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface PlaybackHistoryDao {
    /**
     * Insert a NEW play session. Returns the autogenerated row id so
     * the caller can use it to attach session-scoped bookmarks via
     * [HistoryBookmarkDao].
     */
    @Insert
    suspend fun insertSession(row: PlaybackHistoryEntity): Long

    @Query("SELECT * FROM playback_history ORDER BY lastPlayedAt DESC")
    fun observeAll(): Flow<List<PlaybackHistoryEntity>>

    /** One-shot snapshot — used by trimToCap. */
    @Query("SELECT * FROM playback_history ORDER BY lastPlayedAt DESC")
    suspend fun snapshot(): List<PlaybackHistoryEntity>

    @Query("SELECT * FROM playback_history ORDER BY lastPlayedAt DESC LIMIT 1")
    suspend fun mostRecent(): PlaybackHistoryEntity?

    /**
     * Update position for a specific session (id-based) — used by the
     * 5-second persist tick in PlayerViewModel. Avoid wildcarding
     * across all sessions of the same mediaUri because each session
     * carries its own resume position.
     */
    @Query("UPDATE playback_history SET lastPositionMs = :pos WHERE id = :id")
    suspend fun updatePosition(id: Long, pos: Long)

    /** Compatibility: legacy callers that key by URI update the most recent row. */
    @Query(
        "UPDATE playback_history SET lastPositionMs = :pos " +
            "WHERE id = (SELECT id FROM playback_history WHERE mediaUri = :uri " +
            "ORDER BY lastPlayedAt DESC LIMIT 1)"
    )
    suspend fun updatePositionByUri(uri: String, pos: Long)

    @Query("DELETE FROM playback_history WHERE id = :id")
    suspend fun delete(id: Long)

    @Query("DELETE FROM playback_history WHERE id IN (:ids)")
    suspend fun deleteMany(ids: List<Long>)

    @Query("SELECT * FROM playback_history WHERE id = :id")
    suspend fun get(id: Long): PlaybackHistoryEntity?

    @Query("DELETE FROM playback_history")
    suspend fun deleteAll()
}
